#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker build --tag=cfinfrastructure/destiny ./ci
  docker run -v $PWD:/destiny cfinfrastructure/destiny /destiny/ci/tasks/test/test
popd
