#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker build --tag=cfinfrastructure/destiny ${DOCKERFILE:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci/dockerfiles/destiny"}
  docker run -v $PWD:/destiny -v ${MEGA_CI:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci"}:/mega-ci cfinfrastructure/destiny ${TEST_TASK:-"/mega-ci/scripts/ci/destiny/test"}
popd
